# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PycharmProjects\MiniPythonPro\location_for_pack\pack.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PackForm(object):
    def setupUi(self, PackForm):
        PackForm.setObjectName("PackForm")
        PackForm.resize(789, 627)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Pack_24px.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PackForm.setWindowIcon(icon)
        self.scan_btn = QtWidgets.QPushButton(PackForm)
        self.scan_btn.setEnabled(True)
        self.scan_btn.setGeometry(QtCore.QRect(450, 10, 81, 31))
        self.scan_btn.setObjectName("scan_btn")
        self.scan_jobnum_le = QtWidgets.QLineEdit(PackForm)
        self.scan_jobnum_le.setGeometry(QtCore.QRect(235, 10, 191, 31))
        self.scan_jobnum_le.setObjectName("scan_jobnum_le")
        self.scan_label = QtWidgets.QLabel(PackForm)
        self.scan_label.setGeometry(QtCore.QRect(150, 15, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.scan_label.setFont(font)
        self.scan_label.setObjectName("scan_label")
        self.scan_info_lv = QtWidgets.QListWidget(PackForm)
        self.scan_info_lv.setStyleSheet("QListWidget{border:1px solid gray; color:black; }"
                    "QListWidget::Item{padding-top:6px; padding-bottom:3px; }"
                    "QListWidget::Item:hover{background:skyblue; }"
                    )
        self.scan_info_lv.setGeometry(QtCore.QRect(20, 60, 530, 541))
        self.scan_info_lv.setMouseTracking(False)
        self.scan_info_lv.setObjectName("scan_info_lv")
        self.line = QtWidgets.QFrame(PackForm)
        self.line.setGeometry(QtCore.QRect(10, 35, 551, 31))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(PackForm)
        self.line_2.setGeometry(QtCore.QRect(560, 0, 20, 601))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.clear_gb = QtWidgets.QGroupBox(PackForm)
        self.clear_gb.setEnabled(True)
        self.clear_gb.setGeometry(QtCore.QRect(580, 70, 201, 141))
        self.clear_gb.setStyleSheet("")
        self.clear_gb.setFlat(False)
        self.clear_gb.setCheckable(False)
        self.clear_gb.setObjectName("clear_gb")
        self.clear_all_3_btn = QtWidgets.QPushButton(self.clear_gb)
        self.clear_all_3_btn.setGeometry(QtCore.QRect(10, 30, 181, 41))
        self.clear_all_3_btn.setStyleSheet("background-color: rgb(255, 255, 127);")

        self.clear_all_3_btn.setObjectName("clear_all_3_btn")
        self.clear_single_le = QtWidgets.QLineEdit(self.clear_gb)
        self.clear_single_le.setGeometry(QtCore.QRect(10, 100, 101, 31))
        self.clear_single_le.setText("")
        self.clear_single_le.setObjectName("clear_single_le")
        self.clear_single_btn = QtWidgets.QPushButton(self.clear_gb)
        self.clear_single_btn.setGeometry(QtCore.QRect(130, 100, 61, 31))
        self.clear_single_btn.setObjectName("clear_single_btn")
        self.line_3 = QtWidgets.QFrame(PackForm)
        self.line_3.setGeometry(QtCore.QRect(580, 35, 201, 31))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.login_status_lable = QtWidgets.QLabel(PackForm)
        self.login_status_lable.setGeometry(QtCore.QRect(590, 10, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.login_status_lable.setFont(font)
        self.login_status_lable.setObjectName("login_status_lable")
        self.login_login_lable = QtWidgets.QLabel(PackForm)
        self.login_login_lable.setGeometry(QtCore.QRect(670, 10, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.login_login_lable.setFont(font)
        self.login_login_lable.setAutoFillBackground(False)
        self.login_login_lable.setStyleSheet("color: rgb(255, 0, 0);")
        self.login_login_lable.setObjectName("login_login_lable")
        self.add_gb = QtWidgets.QGroupBox(PackForm)
        self.add_gb.setGeometry(QtCore.QRect(580, 230, 201, 71))
        self.add_gb.setObjectName("add_gb")
        self.add_number_le = QtWidgets.QLineEdit(self.add_gb)
        self.add_number_le.setGeometry(QtCore.QRect(10, 30, 101, 31))
        self.add_number_le.setText("")
        self.add_number_le.setObjectName("add_number_le")
        self.add_btn = QtWidgets.QPushButton(self.add_gb)
        self.add_btn.setGeometry(QtCore.QRect(130, 30, 61, 31))
        self.add_btn.setObjectName("add_btn")
        self.export_gb = QtWidgets.QGroupBox(PackForm)
        self.export_gb.setGeometry(QtCore.QRect(580, 320, 201, 241))
        self.export_gb.setObjectName("export_gb")
        self.export_location_rb = QtWidgets.QRadioButton(self.export_gb)
        self.export_location_rb.setGeometry(QtCore.QRect(30, 25, 101, 21))
        self.export_location_rb.setChecked(True)
        self.export_location_rb.setObjectName("export_location_rb")
        self.export_history_rb = QtWidgets.QRadioButton(self.export_gb)
        self.export_history_rb.setGeometry(QtCore.QRect(30, 106, 91, 20))
        self.export_history_rb.setObjectName("export_history_rb")
        self.export_btn = QtWidgets.QPushButton(self.export_gb)
        self.export_btn.setGeometry(QtCore.QRect(30, 180, 131, 41))
        self.export_btn.setObjectName("export_btn")
        self.export_history_select_de = QtWidgets.QDateEdit(self.export_gb)
        self.export_history_select_de.setEnabled(False)
        self.export_history_select_de.setGeometry(QtCore.QRect(50, 140, 121, 22))
        self.export_history_select_de.setAccelerated(False)
        self.export_history_select_de.setObjectName("export_history_select_de")
        self.export_location_select_cb = QtWidgets.QComboBox(self.export_gb)
        self.export_location_select_cb.setGeometry(QtCore.QRect(50, 60, 69, 22))
        self.export_location_select_cb.setObjectName("export_location_select_cb")
        self.export_location_select_cb.addItem("")
        self.export_location_select_cb.addItem("")
        self.export_location_select_cb.addItem("")
        self.export_location_select_cb.addItem("")
        self.location_lable = QtWidgets.QLabel(PackForm)
        self.location_lable.setGeometry(QtCore.QRect(20, 10, 51, 31))
        self.location_lable.setObjectName("location_lable")
        self.location_num_lable = QtWidgets.QLabel(PackForm)
        self.location_num_lable.setGeometry(QtCore.QRect(80, 11, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.location_num_lable.setFont(font)
        self.location_num_lable.setStyleSheet("color: rgb(255, 0, 0);")
        self.location_num_lable.setObjectName("location_num_lable")

        self.retranslateUi(PackForm)
        QtCore.QMetaObject.connectSlotsByName(PackForm)

    def retranslateUi(self, PackForm):
        _translate = QtCore.QCoreApplication.translate
        PackForm.setWindowTitle(_translate("PackForm", "套装打包"))
        PackForm.setFixedSize(PackForm.width(), PackForm.height())
        self.scan_btn.setText(_translate("PackForm", "录入"))
        self.scan_label.setText(_translate("PackForm", "扫描信息"))
        self.clear_gb.setTitle(_translate("PackForm", "库位清空"))
        self.clear_all_3_btn.setText(_translate("PackForm", "一键清空（满3副库位）"))
        self.clear_single_le.setPlaceholderText(_translate("PackForm", "输入单个库位号"))
        self.clear_single_btn.setText(_translate("PackForm", "清空库位"))
        self.login_status_lable.setText(_translate("PackForm", "当前登录："))
        self.login_login_lable.setText(_translate("PackForm", "工号"))
        self.add_gb.setTitle(_translate("PackForm", "库位增加"))
        self.add_number_le.setPlaceholderText(_translate("PackForm", "单次上限100"))
        self.add_btn.setText(_translate("PackForm", "增加库位"))
        self.export_gb.setTitle(_translate("PackForm", "数据导出"))
        self.export_location_rb.setText(_translate("PackForm", "当前库位信息"))
        self.export_history_rb.setText(_translate("PackForm", "操作历史"))
        self.export_btn.setText(_translate("PackForm", "导出"))
        self.export_location_select_cb.setItemText(0, _translate("PackForm", "全部"))
        self.export_location_select_cb.setItemText(1, _translate("PackForm", "一副"))
        self.export_location_select_cb.setItemText(2, _translate("PackForm", "两副"))
        self.export_location_select_cb.setItemText(3, _translate("PackForm", "满3副"))
        self.location_lable.setText(_translate("PackForm", "库位总数"))
        self.location_num_lable.setText(_translate("PackForm", "总数"))

    def updateLoginLoginStatus(self,login_str):
        _translate = QtCore.QCoreApplication.translate
        self.login_login_lable.setText(_translate("PackForm", login_str))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    widget = QtWidgets.QWidget()
    ui = Ui_PackForm()
    ui.setupUi(widget)
    widget.show()
    sys.exit(app.exec_())
